sudo: required
services:
    - docker

before_install:
    - docker build -t shunal/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true shunal/react-test npm test

after_succcess:
    - docker build -t shunal/multi-client ./client
    - docker build -t shunal/multi-nginx ./nginx 
    - docker build -t shunal/multi-server ./server
    - docker build -t shunal/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push shunal/multi-client
    - docker push shunal/multi-nginx
    - docker push shunal/multi-server
    - docker push shunal/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-416321039911
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY