sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shunal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shunal/react-test npm test
after_success:
  - docker build -t shunal/multi-client ./client
  - docker build -t shunal/multi-nginx ./nginx
  - docker build -t shunal/multi-server ./server
  - docker build -t shunal/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push shunal/multi-client
  - docker push shunal/multi-nginx
  - docker push shunal/multi-server
  - docker push shunal/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-923445559289
  bucket_path: new-multi-docker
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY